In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Yaroslav\Desktop\DataSets\Set25\Airbnb_Open_Data.csv', dtype='string')

df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10,9,10/19/2021,0.21,4,6,286,Clean up and treat the home the way you'd like...,<NA>
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30,45,5/21/2022,0.38,4,2,228,Pet friendly but please confirm with me if the...,<NA>
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,<NA>,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,...,$124,3,0,<NA>,<NA>,5,1,352,"I encourage you to use my kitchen, cooking and...",<NA>
3,1002755,<NA>,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30,270,7/5/2019,4.64,4,1,322,<NA>,<NA>
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10,9,11/19/2018,0.1,3,1,289,"Please no smoking in the house, porch or on th...",<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1,0,<NA>,<NA>,3,1,227,No Smoking No Parties or Events of any kind Pl...,<NA>
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.8046,-73.96545,United States,...,$167,1,1,7/6/2015,0.02,2,2,395,House rules: Guests agree to the following ter...,<NA>
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3,0,<NA>,<NA>,5,1,342,<NA>,<NA>
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2,5,10/11/2015,0.1,3,1,386,<NA>,<NA>
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1,0,<NA>,<NA>,3,1,69,<NA>,<NA>

In [4]:
df = df.drop_duplicates()
df = df.drop(columns=[
                        'host_identity_verified', 'lat', 'long',
                        'country', 'country code', 'instant_bookable',
                        'calculated host listings count','house_rules',
                        'license'
                        ])
df = df.rename({'NAME': 'name', 'Construction year': 'construction year'}, axis="columns")

df.head()

,id,name,host id,host name,neighbourhood group,neighbourhood,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,strict,Private room,2020,$966,$193,10,9,10/19/2021,0.21,4,286
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,moderate,Entire home/apt,2007,$142,$28,30,45,5/21/2022,0.38,4,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,Elise,Manhattan,Harlem,flexible,Private room,2005,$620,$124,3,0,<NA>,<NA>,5,352
3,1002755,<NA>,85098326012,Garry,Brooklyn,Clinton Hill,moderate,Entire home/apt,2005,$368,$74,30,270,7/5/2019,4.64,4,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,moderate,Entire home/apt,2009,$204,$41,10,9,11/19/2018,0.1,3,289

In [5]:
check_unique = ['neighbourhood group', 'cancellation_policy', 'room type', 'construction year']

for elem in check_unique:
    print(df[elem].unique())

<StringArray>
[     'Brooklyn',     'Manhattan',       'brookln',      'manhatan',
        'Queens',            <NA>, 'Staten Island',         'Bronx']
Length: 8, dtype: string
<StringArray>
['strict', 'moderate', 'flexible', <NA>]
Length: 4, dtype: string
<StringArray>
['Private room', 'Entire home/apt', 'Shared room', 'Hotel room']
Length: 4, dtype: string
<StringArray>
['2020', '2007', '2005', '2009', '2013', '2015', '2004', '2008', '2010',
 '2019', '2018', '2006', '2016', '2017', '2021', '2003', '2011', '2012',
 '2022', '2014',   <NA>]
Length: 21, dtype: string

In [6]:
def str_replace_func(columns, values_old, values_new):
    for i in range(len(columns)):
        df[columns[i]] = df[columns[i]].str.replace(values_old[i], values_new[i])
    return df

replace_columns = ['price', 'price', 'service fee', 'reviews per month']
values_old = ['$', ',', '$', '.']
values_new = ['', '', '', ',']

df = df.replace({'brookln': 'Brooklyn', 'manhatan': 'Manhattan'})

str_replace_func(replace_columns, values_old, values_new)

,id,name,host id,host name,neighbourhood group,neighbourhood,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,strict,Private room,2020,966,193,10,9,10/19/2021,"0,21",4,286
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,moderate,Entire home/apt,2007,142,28,30,45,5/21/2022,"0,38",4,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,Elise,Manhattan,Harlem,flexible,Private room,2005,620,124,3,0,<NA>,<NA>,5,352
3,1002755,<NA>,85098326012,Garry,Brooklyn,Clinton Hill,moderate,Entire home/apt,2005,368,74,30,270,7/5/2019,"4,64",4,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,moderate,Entire home/apt,2009,204,41,10,9,11/19/2018,"0,1",3,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Cozy bright room near Prospect Park,77326652202,Mariam,Brooklyn,Flatbush,moderate,Private room,<NA>,696,<NA>,7,12,3/27/2019,"0,44",5,0
102054,57365760,Private Bedroom with Amazing Rooftop View,45936254757,Trey,Brooklyn,Bushwick,flexible,Private room,<NA>,909,<NA>,1,19,8/31/2017,"0,72",3,0
102055,57366313,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,Michael,Brooklyn,Bedford-Stuyvesant,moderate,Entire home/apt,<NA>,387,<NA>,2,50,6/26/2019,"3,12",4,235
102056,57366865,Room & private bathroom in historic Harlem,15593031571,Shireen,Manhattan,Harlem,strict,Private room,<NA>,848,<NA>,2,0,<NA>,<NA>,1,0
102057,57367417,Rosalee Stewart,93578954226,Stanley,Manhattan,Harlem,flexible,Entire home/apt,2011,1128,<NA>,4,22,6/15/2019,"0,85",4,238

In [7]:
def fillna_func(columns, values):
    for i in range(len(columns)):
        df[columns[i]] = df[columns[i]].fillna(values[i])
    return df
    
fillna_columns = ['cancellation_policy', 'service fee', 'last review', 'reviews per month', 'review rate number']
fillna_values = ['unknown', '0', 'no review', '0', '0']

fillna_func(fillna_columns, fillna_values)

,id,name,host id,host name,neighbourhood group,neighbourhood,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,strict,Private room,2020,966,193,10,9,10/19/2021,"0,21",4,286
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,moderate,Entire home/apt,2007,142,28,30,45,5/21/2022,"0,38",4,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,Elise,Manhattan,Harlem,flexible,Private room,2005,620,124,3,0,no review,0,5,352
3,1002755,<NA>,85098326012,Garry,Brooklyn,Clinton Hill,moderate,Entire home/apt,2005,368,74,30,270,7/5/2019,"4,64",4,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,moderate,Entire home/apt,2009,204,41,10,9,11/19/2018,"0,1",3,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Cozy bright room near Prospect Park,77326652202,Mariam,Brooklyn,Flatbush,moderate,Private room,<NA>,696,0,7,12,3/27/2019,"0,44",5,0
102054,57365760,Private Bedroom with Amazing Rooftop View,45936254757,Trey,Brooklyn,Bushwick,flexible,Private room,<NA>,909,0,1,19,8/31/2017,"0,72",3,0
102055,57366313,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,Michael,Brooklyn,Bedford-Stuyvesant,moderate,Entire home/apt,<NA>,387,0,2,50,6/26/2019,"3,12",4,235
102056,57366865,Room & private bathroom in historic Harlem,15593031571,Shireen,Manhattan,Harlem,strict,Private room,<NA>,848,0,2,0,no review,0,1,0
102057,57367417,Rosalee Stewart,93578954226,Stanley,Manhattan,Harlem,flexible,Entire home/apt,2011,1128,0,4,22,6/15/2019,"0,85",4,238

In [8]:
df['neighbourhood group'] = df['neighbourhood group'].fillna(df.groupby('neighbourhood')['neighbourhood group'].transform('last'))

df = df.dropna(subset=['neighbourhood', 'construction year','price', 'minimum nights', 'number of reviews', 'availability 365'])

df

,id,name,host id,host name,neighbourhood group,neighbourhood,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,strict,Private room,2020,966,193,10,9,10/19/2021,"0,21",4,286
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,moderate,Entire home/apt,2007,142,28,30,45,5/21/2022,"0,38",4,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,Elise,Manhattan,Harlem,flexible,Private room,2005,620,124,3,0,no review,0,5,352
3,1002755,<NA>,85098326012,Garry,Brooklyn,Clinton Hill,moderate,Entire home/apt,2005,368,74,30,270,7/5/2019,"4,64",4,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,moderate,Entire home/apt,2009,204,41,10,9,11/19/2018,"0,1",3,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102041,57358580,Cozy home away from home,60176837202,<NA>,Queens,Edgemere,moderate,Private room,2020,946,189,1,76,6/27/2019,"2,84",1,324
102042,57359133,Central Park Views - Private Room & Bathroom,68411243647,<NA>,Manhattan,Upper West Side,strict,Private room,2012,706,141,1,4,8/15/2017,"0,14",4,0
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,<NA>,Manhattan,SoHo,flexible,Entire home/apt,2020,1043,209,2,21,7/1/2019,"0,74",4,343
102044,57360237,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,<NA>,Brooklyn,Bedford-Stuyvesant,flexible,Entire home/apt,2010,809,162,31,4,5/29/2019,"0,16",1,178
102057,57367417,Rosalee Stewart,93578954226,Stanley,Manhattan,Harlem,flexible,Entire home/apt,2011,1128,0,4,22,6/15/2019,"0,85",4,238

In [9]:
df = df.astype({'price': int, 'service fee': int, 'minimum nights': int, 'availability 365': int})

In [10]:
df = df[(df['minimum nights'] >= 0) & (df['availability 365'] >= 0)]

df

,id,name,host id,host name,neighbourhood group,neighbourhood,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,strict,Private room,2020,966,193,10,9,10/19/2021,"0,21",4,286
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,moderate,Entire home/apt,2007,142,28,30,45,5/21/2022,"0,38",4,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,Elise,Manhattan,Harlem,flexible,Private room,2005,620,124,3,0,no review,0,5,352
3,1002755,<NA>,85098326012,Garry,Brooklyn,Clinton Hill,moderate,Entire home/apt,2005,368,74,30,270,7/5/2019,"4,64",4,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,moderate,Entire home/apt,2009,204,41,10,9,11/19/2018,"0,1",3,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102041,57358580,Cozy home away from home,60176837202,<NA>,Queens,Edgemere,moderate,Private room,2020,946,189,1,76,6/27/2019,"2,84",1,324
102042,57359133,Central Park Views - Private Room & Bathroom,68411243647,<NA>,Manhattan,Upper West Side,strict,Private room,2012,706,141,1,4,8/15/2017,"0,14",4,0
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,<NA>,Manhattan,SoHo,flexible,Entire home/apt,2020,1043,209,2,21,7/1/2019,"0,74",4,343
102044,57360237,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,<NA>,Brooklyn,Bedford-Stuyvesant,flexible,Entire home/apt,2010,809,162,31,4,5/29/2019,"0,16",1,178
102057,57367417,Rosalee Stewart,93578954226,Stanley,Manhattan,Harlem,flexible,Entire home/apt,2011,1128,0,4,22,6/15/2019,"0,85",4,238

In [11]:
df.to_csv('Air_bnb_PreCleaned_3.csv', index=False)